// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkGuPwXEVEgUJn78VcGIK0HotU9c6Nkt4',
    appId: '1:684129603620:android:8cc8c3662e4931e10248b1',
    messagingSenderId: '684129603620',
    projectId: 'vidcall-f853e',
    storageBucket: 'vidcall-f853e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK6FYMxFAcc_sV6EEDVafxY-pxiy8_lDE',
    appId: '1:684129603620:ios:e1b9b9209c4d17d40248b1',
    messagingSenderId: '684129603620',
    projectId: 'vidcall-f853e',
    storageBucket: 'vidcall-f853e.firebasestorage.app',
    androidClientId: '684129603620-e1n54li1qmgqt71kd35aua18tnuts09l.apps.googleusercontent.com',
    iosClientId: '684129603620-56mocsicjt9701vlcl7ps0gcsr7iaqc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.zztherapy',
  );
}
