// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF3AmluBl-_AqnMfTPCuSI4uOiWkQ-hfQ',
<<<<<<< HEAD
    appId: '1:911372372113:android:65d2a2d572d7cc564d1730',
=======
    appId: '1:911372372113:android:6ce266d982bb6b174d1730',
>>>>>>> 6caedcda0209c58437b74b5a57398940c89ff7ed
    messagingSenderId: '911372372113',
    projectId: 'matchvibe-d55f9',
    storageBucket: 'matchvibe-d55f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR0AEomxpY08XwsPFY_3i_q3OAV7Up7lc',
    appId: '1:911372372113:ios:891d7b0578f756414d1730',
    messagingSenderId: '911372372113',
    projectId: 'matchvibe-d55f9',
    storageBucket: 'matchvibe-d55f9.firebasestorage.app',
    iosBundleId: 'com.example.zztherapy',
  );
}
